# Generated by Django 4.2.3 on 2023-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0002_well_ink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='privateStatus',
            field=models.BooleanField(default=False),
        ),
    ]
