# Generated by Django 4.2.3 on 2023-09-12 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0004_ink_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ink', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='co_ink', to='inkwell.ink')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='CoAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
