# Generated by Django 4.2.1 on 2023-09-13 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0005_coauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='coAuthor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='co_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='well',
            name='privateStatus',
            field=models.BooleanField(default=False),
        ),
    ]
