# Generated by Django 4.2.3 on 2023-09-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='genre',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(default='', max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.CharField(default='', max_length=120)),
                ('notifiedUser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifiedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
