# Generated by Django 4.2.1 on 2023-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0008_ink_genre_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
