# Generated by Django 4.2.1 on 2023-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0009_ink_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='letterCount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ink',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
