# Generated by Django 4.2.1 on 2023-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0010_ink_lettercount_alter_ink_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
