# Generated by Django 4.2.1 on 2023-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0012_user_coauthorrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceptedRequests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
