# Generated by Django 4.2.3 on 2023-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0013_user_acceptedrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coauthor',
            name='ink',
        ),
        migrations.RemoveField(
            model_name='ink',
            name='coAuthor',
        ),
        migrations.AddField(
            model_name='ink',
            name='coAuthors',
            field=models.ManyToManyField(to='inkwell.coauthor'),
        ),
    ]
