# Generated by Django 4.2.3 on 2023-09-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0014_remove_coauthor_ink_remove_ink_coauthor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InkVersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=120)),
                ('contents', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('originalInk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkwell.ink')),
            ],
        ),
    ]
