# Generated by Django 4.2.3 on 2023-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0015_inkversioncontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='updateStatus',
            field=models.BooleanField(default=False),
        ),
    ]
