# Generated by Django 4.2.3 on 2023-09-23 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0016_ink_updatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
