# Generated by Django 4.2.3 on 2023-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0017_ink_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
