# Generated by Django 4.2.1 on 2023-09-24 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0018_ink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ink',
            name='coAuthors',
            field=models.ManyToManyField(blank=True, to='inkwell.coauthor'),
        ),
        migrations.AlterField(
            model_name='ink',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
