# Generated by Django 4.2.3 on 2023-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0019_alter_ink_coauthors_alter_ink_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='', max_length=250),
        ),
    ]
