# Generated by Django 4.2.1 on 2023-10-08 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0021_user_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ink',
            name='following',
        ),
        migrations.AddField(
            model_name='ink',
            name='ink_following',
            field=models.ManyToManyField(blank=True, related_name='ink_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ink',
            name='coAuthors',
            field=models.ManyToManyField(blank=True, related_name='CoAuthors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CoAuthor',
        ),
    ]
