# Generated by Django 4.2.1 on 2023-10-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0022_remove_ink_following_ink_ink_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterTitle', models.CharField(max_length=64)),
                ('chapterContents', models.TextField()),
                ('chapterInkOrigin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='chapterInkOrigin', to='inkwell.ink')),
            ],
        ),
    ]
