# Generated by Django 4.2.1 on 2023-10-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0023_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapterNumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
