# Generated by Django 4.2.1 on 2023-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0024_chapter_chapternumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
