# Generated by Django 4.2.1 on 2023-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0025_chapter_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapterNumber',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
