# Generated by Django 4.2.3 on 2023-10-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0026_remove_chapter_introduction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InkVersionControl',
        ),
    ]
