# Generated by Django 4.2.1 on 2023-10-24 09:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0031_alter_chapter_chaptercontents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapterContents',
            field=django_quill.fields.QuillField(),
        ),
    ]
