# Generated by Django 4.2.1 on 2023-10-27 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0033_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postCreationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
