# Generated by Django 4.2.1 on 2023-10-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0035_remove_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acceptedRequests',
        ),
    ]
