# Generated by Django 4.2.1 on 2023-11-03 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0036_remove_user_acceptedrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commentCreationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('commentAuthor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
