# Generated by Django 4.2.1 on 2023-11-03 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0038_comment_commentinkorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestedContentChange', django_quill.fields.QuillField()),
                ('requestDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('coAuthor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coAuthor', to=settings.AUTH_USER_MODEL)),
                ('requestedChapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requestedChapter', to='inkwell.chapter')),
            ],
        ),
    ]
