# Generated by Django 4.2.1 on 2023-11-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0039_coauthorrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coauthorrequest',
            old_name='requestedContentChange',
            new_name='chapterContents',
        ),
    ]
