# Generated by Django 4.2.1 on 2023-11-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0042_remove_ink_lettercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coAuthorRequests',
            new_name='YourCoAuthorRequests',
        ),
    ]
