# Generated by Django 4.2.1 on 2023-12-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0043_rename_coauthorrequests_user_yourcoauthorrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ink',
            name='coAuthors',
        ),
    ]
