# Generated by Django 4.2.1 on 2023-12-04 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0044_remove_ink_coauthors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='coAuthors',
            field=models.ManyToManyField(blank=True, related_name='CoAuthors', to=settings.AUTH_USER_MODEL),
        ),
    ]
