# Generated by Django 4.2.1 on 2023-12-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0047_ink_coauthors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverAuthors', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discoverAuthors', to=settings.AUTH_USER_MODEL)),
                ('popularAuthors', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='popularAuthors', to=settings.AUTH_USER_MODEL)),
                ('topAuthors', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topAuthors', to=settings.AUTH_USER_MODEL)),
                ('topCoAuthors', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topCoAuthors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
