# Generated by Django 4.2.1 on 2023-12-14 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0048_discoverauthors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverauthors',
            name='discoverAuthors',
        ),
        migrations.RemoveField(
            model_name='discoverauthors',
            name='popularAuthors',
        ),
        migrations.RemoveField(
            model_name='discoverauthors',
            name='topAuthors',
        ),
        migrations.RemoveField(
            model_name='discoverauthors',
            name='topCoAuthors',
        ),
        migrations.AddField(
            model_name='discoverauthors',
            name='discoverAuthors',
            field=models.ManyToManyField(blank=True, related_name='discoverAuthors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discoverauthors',
            name='popularAuthors',
            field=models.ManyToManyField(blank=True, related_name='popularAuthors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discoverauthors',
            name='topAuthors',
            field=models.ManyToManyField(blank=True, related_name='topAuthors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discoverauthors',
            name='topCoAuthors',
            field=models.ManyToManyField(blank=True, related_name='topCoAuthors', to=settings.AUTH_USER_MODEL),
        ),
    ]
