# Generated by Django 4.2.1 on 2023-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0049_remove_discoverauthors_discoverauthors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=64)),
            ],
        ),
    ]
