# Generated by Django 4.2.1 on 2023-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0050_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='inkwell.tag'),
        ),
    ]
