# Generated by Django 4.2.1 on 2023-12-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0051_ink_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ink',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ink',
            name='genre',
        ),
    ]
