# Generated by Django 4.2.1 on 2023-12-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0052_remove_ink_content_remove_ink_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='YourCoAuthorRequests',
        ),
    ]
