# Generated by Django 4.2.1 on 2024-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0053_remove_user_yourcoauthorrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateAuthorsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalDate', models.DateTimeField(default=(2024, 1, 1))),
            ],
        ),
    ]
