# Generated by Django 4.2.1 on 2024-02-06 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0054_updateauthorsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateauthorsdate',
            name='globalDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
    ]
